os:
  - linux

language: node_js

node_js:
  - stable

before_install:
  - npm install -g xo
  - sudo apt-get install wine1.6-amd64 zip

install:
  - npm install


script:
  - npm run lint

after_success:
  - npm run package-windows
  - npm run package-linux
  - npm run semantic-release




